Repository cetic/helm-nifi, pull requests merged in 2021-11, with the labels that each got.

#169 Update Nifi to 1.14.0 version
  .helmignore
  Chart.yaml
  README.md
  configs/authorizers-empty.xml
  configs/authorizers.xml
  configs/nifi.properties
  configs/state-management.xml
  doc/INSTALLATION.md
  doc/KEYCLOAK.md
  doc/README.md
  doc/USERMANAGEMENT.md
  doc/images/installation/add-realm.png
  doc/images/installation/add-user.png
  doc/images/installation/change-pass.png
  doc/images/installation/client-nifi-created.PNG
  doc/images/installation/client-nifi.png
  doc/images/installation/devops-realm.png
  doc/images/installation/grafana-keycloak-auth.png
  doc/images/installation/john-doe.png
  doc/images/installation/keycloak-clients.png
  doc/images/installation/keycloak-first-screen.png
  doc/images/installation/keycloak-realms.png
  doc/images/installation/keycloak-ui.png
  doc/images/installation/nifi-credentials.PNG
  doc/images/installation/users-page.png
  doc/images/logos/cetic.png
  doc/images/logos/helm.png
  doc/images/logos/keycloak-logo.png
  doc/images/logos/nifi.png
  templates/ingress.yaml
  templates/route.yaml
  templates/service.yaml
  templates/statefulset.yaml
  values.yaml
Labels: documentation, enhancement

#181 bump nifi registry version to support new ingress version
  Chart.yaml
Labels: bug

#186 Add namespace to service monitor
  Chart.yaml
  README.md
  templates/servicemonitor.yaml
  values.yaml
Labels: enhancement
