Repository cetic/helm-nifi, pull requests merged in 2021-06, with the labels that each got.

#147 Basic test in Minikube
  .github/workflows/test.yml
  README.md
Labels: enhancement

#150 Bump nifi registry version
  Chart.yaml
Labels: enhancement

#132 Fix offloading nodes
  Chart.yaml
  templates/statefulset.yaml
Labels: bug

#148 Re-enable safetyValve if OIDC is not enabled / clusterSecure false
  Chart.yaml
  templates/statefulset.yaml
Labels: bug, enhancement
